config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :projects
  root "projects#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/project.rb
class Project < ApplicationRecord
	has_many :technologies
end

app/models/technology.rb
class Technology < ApplicationRecord
  belongs_to :project
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]

  # GET /projects
  # GET /projects.json
  def index
    @projects = Project.all
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def project_params
      params.require(:project).permit(:name, :description, :detailed_description, :photo, :technology)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/layouts/_header.html.erb
<div class="container-fluid d-flex justify-content-center align-items-center wow animate__flipInX" id="header-wrapper"data-wow-duration="4s">
  <div class="header-inner-div py-5 text-center">
    <h1 class="wow animate__bounceInDown" data-wow-duration="5s">Hi There!! I Am Nyaga Andre Roy</h1>
    <h3 class="wow animate__bounceInLeft mb-5" data-wow-duration="10s" >Ruby On Rails Full-Stack Developer(React/Redux)</h3>
    <a class="wow animate__fadeOut" data-wow-delay="1s" data-wow-duration="8s" id="header-about-me-link" href="#about">About Me</a>
  </div>
</div>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-expand-md fixed-top" id="navbar-wrapper">
	<a class="navbar-brand" href="/">Nyaga Roy</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
    <span class="navbar-toggler-icon"><i class="fas fa-sliders-h text-white"></i></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarResponsive">
  	<ul class="navbar-nav ml-auto">
      <li class="nav-item">
        <a class="nav-link" href="#about">About</a>
      </li>
  		<li class="nav-item">
  			<a class="nav-link" href="#projects">Projects</a>
  		</li>
  		<li class="nav-item">
  			<a class="nav-link" href="#contact">Contact</a>
  		</li> 		
  	</ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NyagaAndreRoy</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Group-Itstech is a web based cameroonian tech company.">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/4.0.0/animate.min.css">
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="https://fonts.googleapis.com/css?family=Bevan|Roboto+Slab&display=swap" rel="stylesheet">
  </head>

  <body>
    <%= render "layouts/nav" %>
    <%= yield %>
  </body>
</html>

app/views/projects/index.html.erb
<%= render "layouts/header" %>
<div class="container">
  <h1 class="text-center my-5 wow animate__fadeInLeft text-muted" data-wow-duration="1s" id="about" style="font-weight: bolder; color: black">About Me</h1>
  <div class="row">
    <div class="col-md-4">
      <div class="text-center">
        <div class="">
          <i class="fas fa-laptop-code about-icons wow animate__fadeInDownBig" data-wow-duration="2s"></i>
          <h4 class="card-title pt-3 wow animate__fadeInRight" data-wow-duration="3s">Skills</h4>
          <div class="d-flex justify-content-between flex-wrap wow animate__fadeInLeft" data-wow-duration="2s">
            <ul class="about-skill-list">
              <li class="about-skill-list-item">Ruby</li>
              <li class="about-skill-list-item">Rails</li>
              <li class="about-skill-list-item">Rspec</li>
              <li class="about-skill-list-item">Jest</li>
              <li class="about-skill-list-item">TDD</li>
              <li class="about-skill-list-item">Postgresql</li>
              <li class="about-skill-list-item">SQL</li>
              <li class="about-skill-list-item">React</li>
              <li class="about-skill-list-item">Redux</li>
              <li class="about-skill-list-item">Javascript</li>
              <li class="about-skill-list-item">jQuery</li>              
              <li class="about-skill-list-item">Bootstrap4</li>
              <li class="about-skill-list-item">Git and Github</li>
              <li class="about-skill-list-item">Sqlite3</li>
              <li class="about-skill-list-item">Heroku</li>
              <li class="about-skill-list-item">Netlify</li>
            </ul>
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="text-center">
        <div class="">
          <i class="fas fa-graduation-cap about-icons wow animate__fadeInDownBig" data-wow-duration="2s"></i>
          <h4 class="card-title pt-3 wow animate__zoomIn" data-wow-duration="2s">Education</h4>
          <div class="d-flex justify-content-between flex-wrap wow animate__zoomIn" data-wow-duration="2s">
            <span class="skill-span">Microverse Certificate In Web Development.</span>
            <span class="skill-span">Bachelors In Educational Biology, Universityy Of Buea.</span>
            
          </div>
        </div>
      </div>
    </div>
    <div class="col-md-4">
      <div class="text-center">
        <div class="">
          <i class="fas fa-camera-retro about-icons wow animate__fadeInDownBig" data-wow-duration="2s"></i>
          <h4 class="card-title pt-3 wow animate__fadeInRight" data-wow-duration="2s">Interest</h4>
          <div class="d-flex justify-content-between flex-wrap wow animate__fadeInRight" data-wow-duration="2s">
            <span class="skill-span">Piano</span>
            <span class="skill-span">Football</span>
            <span class="skill-span">Internet</span>
            <span class="skill-span">Animation</span>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="container mt-5" id="overall-div">
  <h1 class="text-center mb-5 wow animate__zoomIn text-muted" data-wow-duration="2s" id="projects" style="font-weight: bolder; color: black">Projects</h1>
  <% @projects.each do |project| %>
    <div class="row mx-auto row-div mb-5 p-3 wow animate__hinge" data-wow-duration="2s">      
        <div class="col-md-6 project-col-divs" id="project-left-div">
          <div class="card text-center">
            <%= image_tag(project.photo, class: "card-img-top", alt: "photo here") %>
          </div>
        </div>
        <div class="col-md-6 project-col-divs" id="project-right-div">
          <div class="card text-center h-100">
            <div class="card card-text my-auto">
              <div class="card-body" style="font-size: 0.8em;">
                <h3 class="card-title d-none d-md-block text-muted" id="project-title"><%= project.name %></h3>
                <h5 class="card-title d-md-none text-muted" id="project-title"><%= project.name %></h5>
                <p class="card-text d-none d-md-block"><%= project.detailed_description %></p>
                <div class="d-flex justify-content-between">
                  <%=link_to("View", project.live_demo, class: "project-links", target: "_blank", data_wow_duration: "1s") %>
                  <%=link_to("Github", project.github_link, class: "project-links", target: "_blank") %>
                </div>
                <div class="d-md-flex justify-content-between mt-2 d-none flex-wrap" id="technology-div">
                  <% project.technologies.each do |tech| %>
                    <span class="technology-span m-1"><%= tech.technology %></span>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
    </div>
  <% end %>
</div>

<div class="container-fluid" id=contact-section>
  <h3 id="contact" class="text-center pt-3 mb-5 text-muted" style="font-weight: bolder; color: black">Contact Me</h3>
  <div class="row">
    <div class="col-md-4"></div>
    <div class="col-md-4 d-flex justify-content-between">
      <a href="https://twitter.com/nyagaandreroy1" target="_blank"><i class="fab fa-twitter wow animate__flash" data-wow-duration="2s" data-wow-iteration="infinite"></i></a>
      <a href="https://www.linkedin.com/in/roy-nyaga-andre/" target="_blank"><i class="fab fa-linkedin-in wow animate__bounce" data-wow-duration="2s" data-wow-iteration="infinite"></i></a>
      <a href="https://web.facebook.com/roy.nyaga.77" target="_blank"><i class="fab fa-facebook-f wow animate__shakeY" data-wow-duration="2s" data-wow-iteration="infinite"></i></a>
      <a href="https://github.com/RoyNyaga" target="_blank"><i class="fab fa-github-alt wow animate__swing" data-wow-duration="2s" data-wow-iteration="infinite"></i></a>
    </div>
    <div class="col-md-4"></div>
    <div class="col-md-12 text-center mt-4 mb-2 wow animate__backInRight" data-wow-duration="2s">
      <i class="fas fa-phone-volume px-2">+237671172775</i>   
      <i class="fas fa-envelope-open-text px-2">nyagaandreroy@gmail.com</i>
    </div>   
  </div>
</div>

  <div class="container-fluid" id="footer">
    <h4 class="text-center">Made by Roy Nyaga © 2020</h4>
  </div>

app/views/projects/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @project.description %>
</p>

<p>
  <strong>Detailed description:</strong>
  <%= @project.detailed_description %>
</p>

<p>
  <strong>Photo:</strong>
  <%= @project.photo %>
</p>

<p>
  <strong>Technology:</strong>
  <%= @project.technology %>
</p>

<%= link_to 'Edit', edit_project_path(@project) %> |
<%= link_to 'Back', projects_path %>